# Generated by Django 6.0.3 on 2026-03-30 15:07

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/avatars/', validators=[accounts.validators.validate_file_size]),
        ),
    ]
